services:
  ollama:
    image: intelanalytics/ipex-llm-inference-cpp-xpu:latest
    container_name: ollama
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    user: "0:0"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      WEBUI_AUTH: "False"
      OLLAMA_BASE_URL: "http://ollama:11434"

volumes:
  ollama:
  open-webui:
